version: "3.8"

services:
  axis_postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: axis_admin
      POSTGRES_PASSWORD: axis_password
      POSTGRES_DB: axisdb
    ports:
      - "5435:5432"
    volumes:
      - axis_postgres_data:/var/lib/postgresql/data
    networks:
      - axis_network

  axis_pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: axis@admin.com
      PGADMIN_DEFAULT_PASSWORD: axisadmin
    ports:
      - "5055:80"
    networks:
      - axis_network

volumes:
  axis_postgres_data:

networks:
  axis_network:
